import logging
from datetime import date

from fastapi import APIRouter, Depends
from fastapi.responses import PlainTextResponse
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from core.database import get_db
from core.security import get_current_user
from models.db_models import Flashcard, Progress, Subject, User
from services.analytics import compute_heatmap, compute_subject_mastery, compute_weak_areas

logger = logging.getLogger(__name__)
router = APIRouter(tags=["analytics"])


@router.get("/dashboard")
async def analytics_dashboard(
    current_user: User = Depends(get_current_user),
    db: AsyncSession = Depends(get_db),
):
    """
    Returns:
      - mastery per subject
      - heatmap (all topics, color-coded)
      - weak_areas (topics <60%)
      - srs_due: count of flashcards due today
      - daily_goal: {reviewed, due}
    """
    subject_result = await db.execute(
        select(Subject).where(Subject.user_id == current_user.id)
    )
    subjects = subject_result.scalars().all()

    mastery_list = []
    for s in subjects:
        m = await compute_subject_mastery(current_user.id, s.id, s.name, db)
        mastery_list.append(m.to_dict())

    heatmap = await compute_heatmap(current_user.id, db)
    weak_areas = await compute_weak_areas(current_user.id, db)

    # SRS due today
    today = date.today()
    due_result = await db.execute(
        select(Flashcard).where(
            Flashcard.user_id == current_user.id,
            Flashcard.next_review_date <= today,
        )
    )
    srs_due = len(due_result.scalars().all())

    # Progress stats
    prog_result = await db.execute(select(Progress).where(Progress.user_id == current_user.id))
    progress = prog_result.scalar_one_or_none()

    return {
        "mastery": mastery_list,
        "heatmap": [e.to_dict() for e in heatmap],
        "weak_areas": weak_areas,
        "srs_due": srs_due,
        "progress": {
            "xp": progress.xp if progress else 0,
            "level": progress.level if progress else 1,
            "streak_days": progress.streak_days if progress else 0,
            "badges": progress.badges if progress else [],
        },
    }


@router.get("/export", response_class=PlainTextResponse)
async def export_study_report(
    current_user: User = Depends(get_current_user),
    db: AsyncSession = Depends(get_db),
):
    """Generate a Markdown study report for the current user."""
    subject_result = await db.execute(
        select(Subject).where(Subject.user_id == current_user.id)
    )
    subjects = subject_result.scalars().all()

    prog_result = await db.execute(select(Progress).where(Progress.user_id == current_user.id))
    progress = prog_result.scalar_one_or_none()

    weak = await compute_weak_areas(current_user.id, db)

    lines = [
        f"# Sarvagna Study Report — {current_user.name}",
        f"_Generated: {date.today().isoformat()}_",
        "",
        "## Profile",
        f"- **Level**: {progress.level if progress else 1}",
        f"- **XP**: {progress.xp if progress else 0}",
        f"- **Streak**: {progress.streak_days if progress else 0} days",
        f"- **Badges**: {', '.join(progress.badges) if progress and progress.badges else 'None'}",
        "",
        "## Subject Mastery",
    ]

    for s in subjects:
        m = await compute_subject_mastery(current_user.id, s.id, s.name, db)
        lines += [
            f"### {s.name}",
            f"- Mastery Score: **{m.mastery_score:.1f}%**",
            f"- Roadmap progress: {m.roadmap_pct:.1f}%",
            f"- Quiz avg: {m.quiz_pct:.1f}%",
            f"- SRS recall: {m.srs_pct:.1f}%",
            "",
        ]

    lines += ["## Weak Areas (quiz score < 60%)"]
    if weak:
        for w in weak:
            lines.append(f"- **{w['topic']}** — {w['score_pct']:.1f}% ({w['quiz_count']} quiz{'es' if w['quiz_count'] != 1 else ''})")
    else:
        lines.append("_No weak areas detected yet. Keep quizzing!_")

    lines += ["", "---", "_Report generated by Sarvagna_"]
    return "\n".join(lines)
